import { readFile, writeFile, mkdir, readdir } from "node:fs/promises";
import { resolve, basename, extname } from "node:path";

const root = resolve(import.meta.dirname, "..");
const inputDir = resolve(root, "input");
const dataDir = resolve(root, "data");

function norm(v){return String(v||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/&/g," and ").replace(/[^a-z0-9]+/g," ").replace(/\s+/g," ").trim()}
function makeId(date,time,home,away){return `${date}|${time}|${norm(home)}|${norm(away)}`.replace(/\s+/g,"-")}
function yearJakarta(){return new Intl.DateTimeFormat("en-US",{timeZone:"Asia/Jakarta",year:"numeric"}).format(new Date())}
function parseDate(d,m){return `${yearJakarta()}-${String(m).padStart(2,"0")}-${String(d).padStart(2,"0")}`}
async function pickInput(kind){const files=(await readdir(inputDir)).filter(f=>extname(f).toLowerCase()===".txt").sort();if(!files.length)throw new Error("Folder input/ tidak memiliki file .txt.");const key=kind==="schedule"?["jadwal","schedule","fixture"]:["prediksi","prediction","predict"];const hit=files.find(f=>key.some(k=>f.toLowerCase().includes(k)));if(hit)return resolve(inputDir,hit);if(files.length===1)return resolve(inputDir,files[0]);return resolve(inputDir,files[0])}
function parseSchedule(text){const out=[];let competition="";for(const raw of text.replace(/\r/g,"").split("\n")){const line=raw.trim();if(!line)continue;const m=line.match(/^(\d{1,2})\/(\d{1,2})\s+(\d{1,2}:\d{2})\s+(.+?)\s+VS\s+(.+?)(?:\s+(\S+))?$/i);if(!m){competition=line;continue}const [,d,mo,time,home,away,handicap=""] = m;const date=parseDate(d,mo);out.push({id:makeId(date,time,home,away),date,time,competition:competition||"FOOTBALL",homeTeam:home.trim(),awayTeam:away.trim(),handicap:handicap.trim(),prediction:"",homeScore:null,awayScore:null,homeCrest:"",awayCrest:"",liveStreamingUrl:"",matchDetailUrl:"",featured:false,status:"UPCOMING",source:"TXT MARIOBOLA"})}return out}
function parsePredictions(text){const out=[];let competition="";for(const raw of text.replace(/\r/g,"").split("\n")){const line=raw.trim();if(!line)continue;const m=line.match(/^(\d{1,2})\/(\d{1,2})\s+(\d{1,2}:\d{2})\s+(.+?)\s+VS\s+(.+?)\s+(\d+)\s*[:\-]\s*(\d+)$/i);if(!m){competition=line;continue}const [,d,mo,time,home,away,h,a]=m;const date=parseDate(d,mo);out.push({id:makeId(date,time,home,away),date,time,competition:competition||"FOOTBALL",homeTeam:home.trim(),awayTeam:away.trim(),prediction:`${h}:${a}`})}return out}
function buildTeams(matches){const map=new Map();for(const m of matches){for(const name of [m.homeTeam,m.awayTeam]){const key=norm(name);if(!map.has(key))map.set(key,{name,normalized:key,logoUrl:"",country:"",confidence:0,matchType:"PENDING"})}}return [...map.values()].sort((a,b)=>a.name.localeCompare(b.name))}
const assert=(c,msg)=>{if(!c)throw new Error(msg)};
async function main(){await mkdir(dataDir,{recursive:true});const scheduleFile=await pickInput("schedule");let predictionFile=null;try{predictionFile=await pickInput("prediction")}catch{}const scheduleText=await readFile(scheduleFile,"utf8");const predictionText=predictionFile&&predictionFile!==scheduleFile?await readFile(predictionFile,"utf8"):"";const matches=parseSchedule(scheduleText);const predictions=parsePredictions(predictionText);assert(matches.length,`${basename(scheduleFile)} tidak menghasilkan pertandingan. Format contoh: 18/08 02:00 Team A VS Team B 0:1/4`);const pmap=new Map(predictions.map(x=>[x.id,x]));let matched=0;for(const m of matches){const p=pmap.get(m.id);if(p){m.prediction=p.prediction;matched++}}const updatedAt=new Date().toISOString();await writeFile(resolve(dataDir,"schedule.json"),JSON.stringify({updatedAt,source:"TXT MARIOBOLA",timezone:"Asia/Jakarta",totalMatches:matches.length,totalPredictions:predictions.length,matchedPredictions:matched,matches},null,2)+"\n");await writeFile(resolve(dataDir,"predictions.json"),JSON.stringify({updatedAt,source:"TXT MARIOBOLA",timezone:"Asia/Jakarta",total:predictions.length,predictions},null,2)+"\n");await writeFile(resolve(dataDir,"teams.json"),JSON.stringify({updatedAt,total:buildTeams(matches).length,teams:buildTeams(matches)},null,2)+"\n");console.log(`Jadwal: ${matches.length} | Prediksi: ${predictions.length} | Cocok: ${matched}`)}
main().catch(e=>{console.error("❌ update-data:",e.message);process.exit(1)})
